#端口号
server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  datasource:
    #用户名
    username: root
    #密码
    password: 123456
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接字符串
    url: jdbc:mysql://127.0.0.1/sprout?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    #数据库连接池 使用druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 200
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-cookie-name: cookie_name
        principal-session-name: session_name
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
      aop-patterns: com.pjf.server.service
      filters: stat,wall
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            update-allow: true
            drop-table-allow: false
            insert-allow: true
            delete-allow: true
  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 118.31.77.208
    #端口号
    port: 6379
    #数据库
    database: 1
    #密码
    password: 123456
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 1000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer

springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
    path: /v3/api-docs
    resolve-schema-properties: false
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/test会自动重定向到swagger页面
    path: /test
  #包扫描路径
  packages-to-scan: com.pjf.server.controller,com.pjf.server.entity
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
    #分组名
    - group: sprout
      #按路径匹配
      packages-to-scan: com.pjf.server.controller,com.pjf.server.entity

